# Site Settings
baseurl: ""
url : "https://jeongrakchoi.github.io"

# Blog Settings
theme_settings :
  title : Jeongrak's Devlog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/profile.jpg
    username : Jeongrak Choi
    description : 웹 퍼블리셔 최정락입니다.<br>웹 표준과 웹 접근성을 준수하며, 의미론적이며 컴포넌트 단위의 구조적인 코드를 생산하는 것을 지향합니다.
    experience :
      - start : 2013-12
        end : 2015-06
        experience : (주)포뎁스(UI 개발 / 주임)
      - start : 2015-06
        end : 2022-06
        experience : (주)아이뱅크 (UI 개발 / 팀장)
      - start : 2022-07
        end : 
        experience : (주)한글과컴퓨터
    skills :
      - skill : HTML5
        value : 95  # Percent value
      - skill : CSS3(SASS)
        value : 90  # Percent value
      - skill : Javascript & jQuery
        value : 85  # Percent value
      - skill : SEO
        value : 85  # Percent value
      - skill : Photoshop
        value : 90  # Percent value
      - skill : Illustrator
        value : 70  # Percent value

  # Icons
  icons :
    email:  jrchoi0123@naver.com
    linkedin:  # Full URL
    github: jeongrakchoi
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: jrchoi0123

  # Disqus
  disqus_shortname : jeongrakchoi-github-io

# Pagination
paginate: 10
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
